version: "3.9"
services:
  controller:
    build: .
    image: 24802117/arouter:latest
    ports:
      - "8080:8080"
    environment:
      - CONTROLLER_ADDR=:8080
      - DB_DSN=
    volumes:
      - ./arouter.db:/app/arouter.db
